#%RAML 0.8
title: I want pizza
version: 0.0.1
baseUri: localhost:3000
/pizza:
  get:
    description: |
      Get some pizza!
    responses:
      200:
        body:
          application/json:
            example: !include examples/pizza.json
            schema: !include schemas/pizzaSchema.json
